feat: First iteration of the voxel engine
aresrpg/aresrpg-engine pull request #1
Opened 2024-02-29 16:34 UTC by piellardj

2024-02-29 16:44 UTC, Sceat requested changes
🎉

2024-02-29 16:44 UTC, Sceat commented on src/lib/terrain/patch/factory/cube.ts
> +import * as THREE from "three";
Might be better to import only what's needed to avoid packaging the entire threejs ?

2024-03-01 20:22 UTC, piellardj commented on src/lib/terrain/patch/factory/cube.ts
> +import * as THREE from "three";
Done in 148afacc736bb6115d13f899397de235a85ce529.
However, my tests show that this does not reduce the bundle size of another project importing "aresrpg-engine" and very basic threejs classes.

2024-03-04 13:04 UTC, Sceat approved these changes

2024-03-04 13:05 UTC, merged